auth_enabled: false
server:
  http_listen_port: 3100
compactor:
  working_directory: /loki/compactor
  max_compaction_parallelism: 1
ingester:
  wal:
    enabled: false
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  max_chunk_age: 1h
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    shared_store: filesystem
    cache_location: /loki/boltdb-shipper-cache
  filesystem:
    directory: /loki/chunks
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
